version: '3.8'
services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: njob
            MYSQL_PASSWORD: test
            MYSQL_DATABASE: njob
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - njob-rest-db
    njob-rest:
        build:
            context: ./njob-rest
            dockerfile: Dockerfile
        environment:
            DB_HOST: db
            DB_DATABASE: njob
            DB_USER: njob
            DB_PASSWORD: test
            AUTH_HOST: njob-auth
        networks:
            - njob-rest-db
            - entrypoint
        depends_on:
            - db
    njob-filesystem:
        build:
            context: ./njob-filesystem
            dockerfile: Dockerfile
        volumes:
            - file-storage:/workspace/app/storage
        networks:
            - entrypoint
    njob-pdf:
        build:
            context: ./njob-pdf
            dockerfile: Dockerfile
        networks:
            - entrypoint
    njob-auth:
        build:
            context: ./njob-auth
            dockerfile: Dockerfile
        networks:
            - entrypoint
    njob-frontend:
        build:
            context: ./njob-frontend
            dockerfile: Dockerfile
        networks:
            - entrypoint
    proxy:
        image: nginx:1.16.0-alpine
        ports:
            - 80:80
        volumes:
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - njob-rest
            - njob-filesystem
        networks:
            - entrypoint

volumes:
    file-storage:
    db-data:

networks:
    njob-rest-db:
    entrypoint: